# Generated by Django 4.2.7 on 2026-05-12 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.IntegerField(help_text='Batch number', validators=[django.core.validators.MinValueValidator(1)])),
                ('batch_limit', models.IntegerField(help_text='Maximum customers allowed in this batch', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['batch_number'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_size', models.IntegerField(default=10, help_text='Number of customers per batch', validators=[django.core.validators.MinValueValidator(1)])),
                ('reset_time', models.TimeField(default='00:00:00', help_text='Time to reset queue numbers daily')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(help_text='Name of the service (e.g., General Inquiry, Bill Payment)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the service', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['service_name'],
                'indexes': [models.Index(fields=['service_name'], name='queues_serv_service_039da1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('queue_number', models.IntegerField(help_text='Queue position number', validators=[django.core.validators.MinValueValidator(1)])),
                ('phone_number', models.CharField(help_text='Customer phone number', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('served', 'Served'), ('skipped', 'Skipped')], default='waiting', help_text='Current queue status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('served_at', models.DateTimeField(blank=True, help_text='Time when customer was served', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(help_text='Batch this queue belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='queues', to='queues.batch')),
                ('served_by', models.ForeignKey(blank=True, help_text='Staff member who served this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_queues', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service requested', on_delete=django.db.models.deletion.PROTECT, related_name='queues', to='queues.service')),
            ],
            options={
                'verbose_name': 'Queue',
                'verbose_name_plural': 'Queues',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('message', models.TextField(blank=True, help_text='Customer feedback message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue', models.OneToOneField(help_text='Queue this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='queues.queue')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_number'], name='queues_batc_batch_n_4af86f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('batch_number',)},
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['status', 'created_at'], name='queues_queu_status_d2a086_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['phone_number'], name='queues_queu_phone_n_22b9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['queue_number'], name='queues_queu_queue_n_68aeb0_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['rating', 'created_at'], name='queues_feed_rating_adf31a_idx'),
        ),
    ]
