# Generated by Django 4.2.7 on 2026-05-12 10:25

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_size', models.IntegerField(default=10, help_text='Number of customers per batch', validators=[django.core.validators.MinValueValidator(1)])),
                ('reset_time', models.TimeField(default='00:00:00', help_text='Time to reset queue numbers daily')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
