# Generated by Django 6.0.5 on 2026-06-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_alter_queue_queue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='called_at',
            field=models.DateTimeField(blank=True, help_text='Time when customer was called', null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='served_at',
            field=models.DateTimeField(blank=True, help_text='Time when customer was served', null=True),
        ),
    ]
